### ISSUE TITLE
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。(错误码：237)

### ISSUE THREAD

**Issue by zzugyl** [Clansty/electron-qq#19]
我尝试登录不同的qq，有些qq正常登录，有些qq提示：
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。(错误码：237)
![2021-06-05_18-02](https://user-images.githubusercontent.com/27466768/120888038-c6216180-c628-11eb-8f9d-789593286313.png)
测试的qq，都是在电脑和手机上常用的。

**Comment by Clansty** [comment]
最近腾讯风控严格，建议在常用地点登录，不要出现需要过滑块的情况

可以参考以下内容：

https://github.com/mamoe/mirai/issues/1277

**Comment by Clansty** [comment]
听说最近风控已经降低了，现在可以再试试

**Comment by zzugyl** [comment]
我按照你给链接方法，生成了device.json。我应该放在electron-qq的哪个路径呢？我用的是AppImage文件。

**Comment by Clansty** [comment]
`~/.config/electron-qq/data/qq号`

**Comment by zzugyl** [comment]
electron-qq下面的device-qq.json格式是明文字符串：
` cat device-1204****.json            
{
    "--begin--":    "该设备文件由账号作为seed自动生成，每个账号生成的文件相同。",
    "product":      "MRS4S",
    "device":       "HIM188MOE",
    "board":        "MIRAI-YYDS",
    "brand":        "OICQX",
    "model":        "Konata 2020",
    "wifi_ssid":    "TP-LINK-****",
    "bootloader":   "U-boot",
    "android_id":   "OICQX.*****.1701",
    "boot_id":      "cc1390aa-ac36-****-****-********",
    "proc_version": "Linux version 4.19.71-44086 (konata@takayama.github.com)",
    "mac_address":  "00:50:1D:**:**:**",
    "ip_address":   "10.0.93.154",
    "imei":         "861838030*****6",
    "incremental":  "177272****",
    "--end--":      "修改后可能需要重新验证设备。"
}%`

从app获取的device.jsong格式是这样的：
`  "display": [
        77,
        73,
        82,
        65,
        73,
        46,
        54,
        53,
        51,
        57,
        50,
        54,
        46,
        48,
        48,
        49
    ],
    "product": [
        109,
        105,
        114,
        97,
        105
    ],
    "device": [
        109,
        105,
        114,
        97,
        105
    ],
    "board": [
        109,
        105,
        114,
        97,
        105
    ],
    "brand": [
......................
`

直接替换，登录electron-qq，没反应。
`[2021-06-10T01:49:35.220] [MARK] [aPad:1204****] - ----------
[2021-06-10T01:49:35.220] [MARK] [aPad:1204****] - Package Version: oicq@1.17.1 (Released on 2021/5/21)
[2021-06-10T01:49:35.220] [MARK] [aPad:1204****] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-06-10T01:49:35.220] [MARK] [aPad:1204****] - ----------
`

**Comment by Clansty** [comment]
啊这 那 你就把各个字段都填写到它们应该在的位置吧

oicq 和 mirai 不太一样的

**Comment by takayama-lily** [comment]
没什么好办法，可以换几个ip试试，我电脑上(海外)就能正常拉验证码，有的人就不行。
真机拉应该是没问题的，但是要自己抓ticket。
