### ISSUE TITLE
ubuntu 20.10下desktop文件没有icon显示

### ISSUE THREAD

**Issue by jingle0927** [Clansty/electron-qq#24]
sudo dpkg -i electron-qq_1.4.8_amd64.deb 
正在选中未选择的软件包 electron-qq。
(正在读取数据库 ... 系统当前共安装有 194287 个文件和目录。)
准备解压 electron-qq_1.4.8_amd64.deb  ...
正在解压 electron-qq (1.4.8) ...
正在设置 electron-qq (1.4.8) ...
**chmod: 无法访问 '/opt/electron-qq/chrome-sandbox': 没有那个文件或目录**
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu4) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...

还有一个chmod提示

**Comment by jingle0927** [comment]
![20210630919](https://user-images.githubusercontent.com/26103116/121277777-e9d3f880-c903-11eb-8cb2-c5d9ef328f28.png)

**Comment by Clansty** [comment]
是的，electron builder 打包的问题
