### ISSUE TITLE
不同聊天的输入框通用

### ISSUE THREAD

**Issue by lixiang810** [Clansty/electron-qq#28]
在A聊天输入框里输入内容，切换到B聊天，发现输入框内容没有变化，极易造成消息误发。  
应当使不同聊天的输入框相互独立，即使做不到 / 难以实现，在切换聊天时也应当自动清空输入框（或者至少加一个设置项）。

**Comment by Clansty** [comment]
在旧版本中是清空输入框的

后来我觉得为了方便（在错误的对话框里输入之后跳转到正确的对话框）以及防止手滑切换对话框时消息丢失就把自动清空删了
