### ISSUE TITLE
无法显示任何图片

### ISSUE THREAD

**Issue by Hulenkius** [Clansty/electron-qq#33]
net::ERR_PROXY_CONNECTION_FAILED

x86_64 Linux 5.10.41-1-MANJARO
通过debtap将deb包转化后用pacman安装
![螢幕快照_2021-06-15_12-13-26](https://user-images.githubusercontent.com/32562298/121992034-628af700-cdd3-11eb-9ccb-ed3b9ae06010.png)

**Comment by Clansty** [comment]
请检查你的代理设置（`$HTTP_PROXY`  `$HTTPS_PROXY`）

另外有提供 pacman 包的，不需要使用 deb 转换安装

**Comment by Hulenkius** [comment]
已解决。
