### ISSUE TITLE
图片消息的气泡尺寸不正确

### ISSUE THREAD

**Issue by comradez** [Clansty/electron-qq#37]
版本是AUR的1.5.5
![Screenshot_20210617_235048](https://user-images.githubusercontent.com/9498051/122431471-11dbef80-cfc7-11eb-9208-e1edf85b4f01.png)
有些长宽比比较小的图片没有遇到这个问题，但是比较长的图气泡尺寸会不正确
（说起来今天才从archwiki上看到这个软件包的推荐，没想到刚装上，吐槽了一句“联系人加载好慢”就更新了，还优化了联系人加载方式，好巧……

**Comment by Clansty** [comment]
你是把窗口拉小了吧qwq

**Comment by comradez** [comment]
确实全屏之后就没有这个问题了（挠头）
但是1960×1470也应该不算太小了……还是会有这个问题
