### ISSUE TITLE
请问登录验证码弹窗白屏，如何解决

### ISSUE THREAD

**Issue by isyry** [Clansty/electron-qq#40]
通过就全白

**Comment by Clansty** [comment]
那很有可能是截取 ticket 的时候遇到了问题呢，可以打开控制台看看什么情况

另外由于风控原因很可能在电脑上拉验证码的 ticket 是无法正常登录的，建议你在常用地点登录呢

**Comment by ForkFG** [comment]
我也是，是在常用地点登录，终端没有打印任何信息。

**Comment by ForkFG** [comment]
不需要验证码时可以正常登录，有点离谱

**Comment by Clansty** [comment]
fixed
