### ISSUE TITLE
引用回复(加载之前的消息)会打乱消息的排列顺序

### ISSUE THREAD

**Issue by Logiase** [Clansty/electron-qq#5]
![image](https://user-images.githubusercontent.com/37612226/119318439-e3127800-bcab-11eb-8d37-f47cc836294a.png)

如图

两条之间还有数条消息

**Comment by Clansty** [comment]
妳是 lowdb 数据库格式？（未使用 MongoDB？）

mongoDB 我是加入了自动排序的，lowdb 的性能太差了，我没有在使用，并且正在减少对它的支持

建议使用 MongoDB 作为数据存储后端。安装比较简单，Arch Linux 例子：
```bash
yay -S mongodb-bin
sudo systemctl enable --now mongodb
```

**Comment by Logiase** [comment]
> 妳是 lowdb 数据库格式？（未使用 MongoDB？）
> 
> mongoDB 我是加入了自动排序的，lowdb 的性能太差了，我没有在使用，并且正在减少对它的支持
> 
> 建议使用 MongoDB 作为数据存储后端。安装比较简单，Arch Linux 例子：
> 
> ```shell
> yay -S mongodb-bin
> sudo systemctl enable --now mongodb
> ```

懂了
