### ISSUE TITLE
消息同步异常

### ISSUE THREAD

**Issue by ho229v3666** [Clansty/electron-qq#54]
接收不到登陆前发的消息
有时候登陆着也接收不到消息

version: 1.5.7
OS: OpenSUSE

**Comment by Clansty** [comment]
本来就接收不到登录前消息

**Comment by ho229v3666** [comment]
那登陆之后呢？我自己发的消息有时候收不到

**Comment by Clansty** [comment]
自己发的私聊消息是收不到，但是群消息可以

**Comment by ho229v3666** [comment]
群消息有时也不行，所以说这个bug可以解决吗

**Comment by Clansty** [comment]
啊这，我也不知道

**Comment by JerryHM11** [comment]
这个消息发送的话，就是手机上发出去的消息（不是自己），电脑端没有；电脑上发送的，手机上有。

**Comment by ho229v3666** [comment]
大概是这样的

**Comment by Clansty** [comment]
> 这个消息发送的话，就是手机上发出去的消息（不是自己），电脑端没有；电脑上发送的，手机上有。

私聊是这样的，群聊是可以同步的

所以提供了一个获取历史消息的功能

**Comment by JerryHM11** [comment]
我试了一下，确实可以，私聊暂不支持，不过足够了。非常感谢作者的努力。
