### ISSUE TITLE
输入框反应慢甚至卡住

### ISSUE THREAD

**Issue by CharlieYu4994** [Clansty/electron-qq#55]
## 环境
操作系统： Manjaro Linux
KDE Plasma 版本： 5.21.5
KDE 框架版本： 5.82.0
Qt 版本： 5.15.2
内核版本： 5.13.0-1-MANJARO
操作系统类型： 64-位
图形平台： X11
处理器： 8 × AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
内存： 14.6 GiB 内存
图形处理器： AMD Radeon™ Vega 8 Graphics
输入法：fcitx5

软件是最新的 appimage 打包

## 问题描述
在运行超过一段时间后输入框反应会变慢，甚至彻底卡住，原因不明

**Comment by Clansty** [comment]
如果是窗口中显示的消息很多的话是会出现这样的情况，应该是因为 dom 节点和事件触发器过多而卡。我们会在未来的版本里努力修复

**Comment by CharlieYu4994** [comment]
> 如果是窗口中显示的消息很多的话是会出现这样的情况，应该是因为 dom 节点和事件触发器过多而卡。我们会在未来的版本里努力修复

谢谢☺️
