### ISSUE TITLE
Manjaro无法正常登录

### ISSUE THREAD

**Issue by SHIINASAMA** [Clansty/electron-qq#60]
输入基本信息后点击Login弹出验证码对话框 ，
验证完成后对话框没有自动关闭（当然父窗体处于Disable状态）并且是白屏。
尝试过Reinstall，关闭QQ登录检测，均无效。
一直是活生生的卡着，百度也查不到相关资料，issues未找到有效信息。

我的配置是
 OS: Manjaro 21.1.0 Pahvo
 Kernel: x86_64 Linux 5.10.49-1-MANJARO
 Uptime: 30m
 Packages: 1362
 Shell: zsh 5.8
 Resolution: 2560x1600
 DE: KDE 5.84.0 / Plasma 5.22.3
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: McMojave-circle-green-dark
 Disk: 28G / 77G (38%)
 CPU: AMD Ryzen 7 4800U with Radeon Graphics @ 16x 1.8GHz
 GPU: AMD RENOIR (DRM 3.40.0, 5.10.49-1-MANJARO, LLVM 12.0.0)

**Comment by SakuraiLH** [comment]
AUR?

**Comment by SHIINASAMA** [comment]
> AUR?

是的，用yay安装的

**Comment by SakuraiLH** [comment]
> > AUR?
> 
> 是的，用yay安装的

作为一个纯路人，我得提醒您: AUR的全称是 Arch Linux User Repository。这也就意味着 AUR 的包裹仅仅在 Arch Linux 这一滚动发行版上进行测试过，而且它面向的用户群体也仅仅应该是 Archlinux 用户。作为一名 Manjaro 用户，在没有解决方案的情况下，我建议您使用 Electron QQ 的 AppImage 版本。这应该会解决您的问题。

**Comment by SStvorec** [comment]
这边建议你跟随SakuraiLH的建议，**毕竟AUR仅在Arch上测试过，不代表Manjaro的测试结果**

**Comment by SHIINASAMA** [comment]
> > > AUR?
> > 
> > 
> > 是的，用yay安装的
> 
> 作为一个纯路人，我得提醒您: AUR的全称是 Arch Linux User Repository。这也就意味着 AUR 的包裹仅仅在 Arch Linux 这一滚动发行版上进行测试过，而且它面向的用户群体也仅仅应该是 Archlinux 用户。作为一名 Manjaro 用户，在没有解决方案的情况下，我建议您使用 Electron QQ 的 AppImage 版本。这应该会解决您的问题。

这依然不适用我的机器，暂时放弃了

**Comment by Clansty** [comment]
> 这边建议你跟随SakuraiLH的建议，**毕竟AUR仅在Arch上测试过，不代表Manjaro的测试结果**

如果 Manjaro 使用的 Electron 版本是 12 或者 13 的话是可以正常使用的

**Comment by Clansty** [comment]
验证码在 1.5.7 版本有不会正常提交的 bug，可以降级使用更老的版本，或者使用 2.0 的测试版本
